---
- hosts: all
  become: yes
  tasks:
    - name: Debian 10
      block:
        - name: Install apt key
          apt_key:
            url: https://apt.releases.hashicorp.com/gpg
            state: present
        - name: Install apt repo
          apt_repository:
            repo: "deb [arch=amd64] https://apt.releases.hashicorp.com buster main"
            state: present
            update_cache: yes
        - name: install packer
          apt:
            name: packer
            state: present
      when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "10")
