---
- hosts: all
  become: yes
  pre_tasks:
  - name: OS Check
    debug:
      msg: System {{ inventory_hostname }} not supported
      verbosity: 1
    when: (ansible_facts['os_family'] != "RedHat") or (ansible_facts['os_family'] != "Debian")
  - name: Check for yum-utils
    yum:
      name: 'yum-utils'
      state: present
    when: (ansible_facts['os_family'] != "RedHat" and ansible_facts['distribution'] == "7")

  tasks:
  - name: apt - Upgrade everything
    apt:
      update_cache: yes
      upgrade: yes
    when: ansible_facts['os_family'] == "Debian"
  - name: yum - Upgrade everything
    yum:
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == "RedHat"
  - name: check needs-restarting - el7
    command: 'needs-restarting -r'
    failed_when: false
    register: needs_restarting
    changed_when: needs_restarting.rc == 1
    notify: restart
    when: (ansible_facts['os_family'] != "RedHat" and ansible_facts['distribution'] == "7")
  - name: check reboot required - Ubuntu
    shell: "[ -f /var/run/reboot-required ]"
    failed_when: false
    register: reboot_required
    changed_when: reboot_required.rc == 0
    notify: restart
    when: (ansible_facts['distribution'] == "Ubuntu")

  handlers:
  - name: restart
    reboot: