---
- hosts: Ubuntu
  become: yes
  pre_tasks:
  - name: OS Check
    debug:
      msg: System {{ inventory_hostname }} not supported
      verbosity: 1
    when: ansible_facts['distribution'] != "Ubuntu"
  tasks:
    - name: Ubuntu apt dist-upgrade
      apt:
        update_cache: yes
        upgrade: dist
    - name: check reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: reboot 
      reboot:
      when: reboot_required.stat.exists == true
